//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiiiChain.DataAgent {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FiiiChain.DataAgent.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 53222 的本地化字符串。
        /// </summary>
        internal static string MainnetPort {
            get {
                return ResourceManager.GetString("MainnetPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Storage 的本地化字符串。
        /// </summary>
        internal static string MainnetStoragePath {
            get {
                return ResourceManager.GetString("MainnetStoragePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 63222 的本地化字符串。
        /// </summary>
        internal static string MainnetTrackerPort {
            get {
                return ResourceManager.GetString("MainnetTrackerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 192.168.31.58 的本地化字符串。
        /// </summary>
        internal static string MainnetTrackerServer {
            get {
                return ResourceManager.GetString("MainnetTrackerServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 53223 的本地化字符串。
        /// </summary>
        internal static string TestnetPort {
            get {
                return ResourceManager.GetString("TestnetPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Storage_Test 的本地化字符串。
        /// </summary>
        internal static string TestnetStoragePath {
            get {
                return ResourceManager.GetString("TestnetStoragePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 63223 的本地化字符串。
        /// </summary>
        internal static string TestnetTrackerPort {
            get {
                return ResourceManager.GetString("TestnetTrackerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 192.168.31.58 的本地化字符串。
        /// </summary>
        internal static string TestnetTrackerServer {
            get {
                return ResourceManager.GetString("TestnetTrackerServer", resourceCulture);
            }
        }
    }
}
